export const PRODUCT_LIST_REQUEST = 'PRODUCT_LIST_REQUEST'
export const PRODUCT_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS'
export const PRODUCT_LIST_FAIL = 'PRODUCT_LIST_FAIL'

export const PRODUCT_DETAILS_REQUEST = 'PRODUCT_DETAILS_REQUEST'
export const PRODUCT_DETAILS_SUCCESS = 'PRODUCT_DETAILS_SUCCESS'
export const PRODUCT_DETAILS_FAIL = 'PRODUCT_DETAILS_FAIL'

export const PRODUCT_DELETE_REQUEST = 'PRODUCT_DELETE_REQUEST'
export const PRODUCT_DELETE_SUCCESS = 'PRODUCT_DELETE_SUCCESS'
export const PRODUCT_DELETE_FAIL = 'PRODUCT_DELETE_FAIL'

export const PRODUCT_CREATE_REQUEST = 'PRODUCT_CREATE_REQUEST'
export const PRODUCT_CREATE_SUCCESS = 'PRODUCT_CREATE_SUCCESS'
export const PRODUCT_CREATE_FAIL = 'PRODUCT_CREATE_FAIL'
export const PRODUCT_CREATE_RESET = 'PRODUCT_CREATE_RESET'

export const PRODUCT_UPDATE_REQUEST = 'PRODUCT_UPDATE_REQUEST'
export const PRODUCT_UPDATE_SUCCESS = 'PRODUCT_UPDATE_SUCCESS'
export const PRODUCT_UPDATE_FAIL = 'PRODUCT_UPDATE_FAIL'
export const PRODUCT_UPDATE_RESET = 'PRODUCT_UPDATE_RESET'

export const PRODUCT_CREATE_REVIEW_REQUEST = 'PRODUCT_CREATE_REVIEW_REQUEST'
export const PRODUCT_CREATE_REVIEW_SUCCESS = 'PRODUCT_CREATE_REVIEW_SUCCESS'
export const PRODUCT_CREATE_REVIEW_FAIL = 'PRODUCT_CREATE_REVIEW_FAIL'
export const PRODUCT_CREATE_REVIEW_RESET = 'PRODUCT_CREATE_REVIEW_RESET'


export const PRODUCT_TOP_REQUEST = 'PRODUCT_TOP_REQUEST'
export const PRODUCT_TOP_SUCCESS = 'PRODUCT_TOP_SUCCESS'
export const PRODUCT_TOP_FAIL = 'PRODUCT_TOP_FAIL'

export const PRODUCT_POPULAR_REQUEST = 'PRODUCT_POPULAR_REQUEST'
export const PRODUCT_POPULAR_SUCCESS = 'PRODUCT_POPULAR_SUCCESS'
export const PRODUCT_POPULAR_FAIL = 'PRODUCT_POPULAR_FAIL'

export const PRODUCT_TOP_SELLING_REQUEST = 'PRODUCT_TOP_SELLING_REQUEST'
export const PRODUCT_TOP_SELLING_SUCCESS = 'PRODUCT_TOP_SELLING_SUCCESS'
export const PRODUCT_TOP_SELLING_FAIL = 'PRODUCT_TOP_SELLING_FAIL'

export const PRODUCT_CREATE_INFO_REQUEST = 'PRODUCT_CREATE_INFO_REQUEST'
export const PRODUCT_CREATE_INFO_SUCCESS = 'PRODUCT_CREATE_INFO_SUCCESS'
export const PRODUCT_CREATE_INFO_FAIL = 'PRODUCT_CREATE_INFO_FAIL'
export const PRODUCT_CREATE_INFO_RESET = 'PRODUCT_CREATE_INFO_RESET'


export const PRODUCT_UPDATE_INFO_REQUEST = 'PRODUCT_UPDATE_INFO_REQUEST'
export const PRODUCT_UPDATE_INFO_SUCCESS = 'PRODUCT_UPDATE_INFO_SUCCESS'
export const PRODUCT_UPDATE_INFO_FAIL = 'PRODUCT_UPDATE_INFO_FAIL'
export const PRODUCT_UPDATE_INFO_RESET = 'PRODUCT_UPDATE_INFO_RESET'

export const PRODUCT_DELETE_INFO_REQUEST = 'PRODUCT_DELETE_INFO_REQUEST'
export const PRODUCT_DELETE_INFO_SUCCESS = 'PRODUCT_DELETE_INFO_SUCCESS'
export const PRODUCT_DELETE_INFO_FAIL = 'PRODUCT_DELETE_INFO_FAIL'

export const PRODUCT_BRAND_REQUEST = 'PRODUCT_BRAND_REQUEST'
export const PRODUCT_BRAND_SUCCESS = 'PRODUCT_BRAND_SUCCESS'
export const PRODUCT_BRAND_FAIL = 'PRODUCT_BRAND_FAIL'
export const PRODUCT_BRAND_RESET = 'PRODUCT_BRAND_RESET'

export const PRODUCT_BRAND_DETAILS_REQUEST = 'PRODUCT_BRAND_DETAILS_REQUEST'
export const PRODUCT_BRAND_DETAILS_SUCCESS = 'PRODUCT_BRAND_DETAILS_SUCCESS'
export const PRODUCT_BRAND_DETAILS_FAIL = 'PRODUCT_BRAND_DETAILS_FAIL'
export const PRODUCT_BRAND_DETAILS_RESET = 'PRODUCT_BRAND_DETAILS_RESET'

export const PRODUCT_BRAND_DELETE_REQUEST = 'PRODUCT_BRAND_DELETE_REQUEST'
export const PRODUCT_BRAND_DELETE_SUCCESS = 'PRODUCT_BRAND_DELETE_SUCCESS'
export const PRODUCT_BRAND_DELETE_FAIL = 'PRODUCT_BRAND_DELETE_FAIL'
export const PRODUCT_BRAND_DELETE_RESET = 'PRODUCT_BRAND_DELETE_RESET'

export const PRODUCT_BRAND_UPDATE_REQUEST = 'PRODUCT_BRAND_UPDATE_REQUEST'
export const PRODUCT_BRAND_UPDATE_SUCCESS = 'PRODUCT_BRAND_UPDATE_SUCCESS'
export const PRODUCT_BRAND_UPDATE_FAIL = 'PRODUCT_BRAND_UPDATE_FAIL'
export const PRODUCT_BRAND_UPDATE_RESET = 'PRODUCT_BRAND_UPDATE_RESET'

export const PRODUCT_BRAND_SET_REQUEST = 'PRODUCT_BRAND_SET_REQUEST'
export const PRODUCT_BRAND_SET_SUCCESS = 'PRODUCT_BRAND_SET_SUCCESS'
export const PRODUCT_BRAND_SET_FAIL = 'PRODUCT_BRAND_SET_FAIL'
export const PRODUCT_BRAND_SET_RESET = 'PRODUCT_BRAND_SET_RESET'

export const PRODUCT_CATEGORY_SET_REQUEST = 'PRODUCT_CATEGORY_SET_REQUEST'
export const PRODUCT_CATEGORY_SET_SUCCESS = 'PRODUCT_CATEGORY_SET_SUCCESS'
export const PRODUCT_CATEGORY_SET_FAIL = 'PRODUCT_CATEGORY_SET_FAIL'
export const PRODUCT_CATEGORY_SET_RESET = 'PRODUCT_CATEGORY_SET_RESET'


export const PRODUCT_CATEGORY_REQUEST = 'PRODUCT_CATEGORY_REQUEST'
export const PRODUCT_CATEGORY_SUCCESS = 'PRODUCT_CATEGORY_SUCCESS'
export const PRODUCT_CATEGORY_FAIL = 'PRODUCT_CATEGORY_FAIL'
export const PRODUCT_CATEGORY_RESET = 'PRODUCT_CATEGORY_RESET'

export const PRODUCT_BRAND_LIST_REQUEST = 'PRODUCT_BRAND_LIST_REQUEST'
export const PRODUCT_BRAND_LIST_SUCCESS = 'PRODUCT_BRAND_LIST_SUCCESS'
export const PRODUCT_BRAND_LIST_FAIL = 'PRODUCT_BRAND_LIST_FAIL'


export const PRODUCT_CATEGORY_DELETE_REQUEST = 'PRODUCT_CATEGORY_DELETE_REQUEST'
export const PRODUCT_CATEGORY_DELETE_SUCCESS = 'PRODUCT_CATEGORY_DELETE_SUCCESS'
export const PRODUCT_CATEGORY_DELETE_FAIL = 'PRODUCT_CATEGORY_DELETE_FAIL'
export const PRODUCT_CATEGORY_DELETE_RESET = 'PRODUCT_CATEGORY_DELETE_RESET'

export const PRODUCT_CATEGORY_UPDATE_REQUEST = 'PRODUCT_CATEGORY_UPDATE_REQUEST'
export const PRODUCT_CATEGORY_UPDATE_SUCCESS = 'PRODUCT_CATEGORY_UPDATE_SUCCESS'
export const PRODUCT_CATEGORY_UPDATE_FAIL = 'PRODUCT_CATEGORY_UPDATE_FAIL'
export const PRODUCT_CATEGORY_UPDATE_RESET = 'PRODUCT_CATEGORY_UPDATE_RESET'

export const PRODUCT_CATEGORY_DETAILS_REQUEST = 'PRODUCT_CATEGORY_DETAILS_REQUEST'
export const PRODUCT_CATEGORY_DETAILS_SUCCESS = 'PRODUCT_CATEGORY_DETAILS_SUCCESS'
export const PRODUCT_CATEGORY_DETAILS_FAIL = 'PRODUCT_CATEGORY_DETAILS_FAIL'
export const PRODUCT_CATEGORY_DETAILS_RESET = 'PRODUCT_CATEGORY_DETAILS_RESET'

export const PRODUCT_CATEGORY_LIST_REQUEST = 'PRODUCT_CATEGORY_LIST_REQUEST'
export const PRODUCT_CATEGORY_LIST_SUCCESS = 'PRODUCT_CATEGORY_LIST_SUCCESS'
export const PRODUCT_CATEGORY_LIST_FAIL = 'PRODUCT_CATEGORY_LIST_FAIL'
export const PRODUCT_CATEGORY_LIST_RESET = 'PRODUCT_CATEGORY_LIST_RESET'

export const PRODUCT_BY_CATEGORY_REQUEST = 'PRODUCT_BY_CATEGORY_REQUEST'
export const PRODUCT_BY_CATEGORY_SUCCESS = 'PRODUCT_BY_CATEGORY_SUCCESS'
export const PRODUCT_BY_CATEGORY_FAIL = 'PRODUCT_BY_CATEGORY_FAIL'
export const PRODUCT_BY_CATEGORY_RESET = 'PRODUCT_BY_CATEGORY_RESET'

export const PRODUCT_CATEGORY_TOP_REQUEST = 'PRODUCT_CATEGORY_TOP_REQUEST'
export const PRODUCT_CATEGORY_TOP_SUCCESS = 'PRODUCT_CATEGORY_TOP_SUCCESS'
export const PRODUCT_CATEGORY_TOP_FAIL = 'PRODUCT_CATEGORY_TOP_FAIL'
export const PRODUCT_CATEGORY_TOP_RESET = 'PRODUCT_CATEGORY_TOP_RESET'


export const PRODUCT_RATED_REQUEST = 'PRODUCT_RATED_REQUEST'
export const PRODUCT_RATED_SUCCESS = 'PRODUCT_RATED_SUCCESS'
export const PRODUCT_RATED_FAIL = 'PRODUCT_RATED_FAIL'
export const PRODUCT_RATED_RESET = 'PRODUCT_RATED_RESET'

export const PRODUCT_HIGHPRICE_REQUEST = 'PRODUCT_HIGHPRICE_REQUEST'
export const PRODUCT_HIGHPRICE_SUCCESS = 'PRODUCT_HIGHPRICE_SUCCESS'
export const PRODUCT_HIGHPRICE_FAIL = 'PRODUCT_HIGHPRICE_FAIL'
export const PRODUCT_HIGHPRICE_RESET = 'PRODUCT_HIGHPRICE_RESET'

export const PRODUCT_LOWPRICE_REQUEST = 'PRODUCT_LOWPRICE_REQUEST'
export const PRODUCT_LOWPRICE_SUCCESS = 'PRODUCT_LOWPRICE_SUCCESS'
export const PRODUCT_LOWPRICE_FAIL = 'PRODUCT_LOWPRICE_FAIL'
export const PRODUCT_LOWPRICE_RESET = 'PRODUCT_LOWPRICE_RESET'

export const PRODUCT_NUMREVIEWS_REQUEST = 'PRODUCT_NUMREVIEWS_REQUEST'
export const PRODUCT_NUMREVIEWS_SUCCESS = 'PRODUCT_NUMREVIEWS_SUCCESS'
export const PRODUCT_NUMREVIEWS_FAIL = 'PRODUCT_NUMREVIEWS_FAIL'
export const PRODUCT_NUMREVIEWS_RESET = 'PRODUCT_NUMREVIEWS_RESET'

// export const PRODUCT_LIST_INFO_REQUEST = 'PRODUCT_LIST_INFO_REQUEST'
// export const PRODUCT_LIST_INFO_SUCCESS = 'PRODUCT_LIST_INFO_SUCCESS'
// export const PRODUCT_LIST_INFO_FAIL = 'PRODUCT_LIST_INFO_FAIL'

// export const PRODUCT_UPDATE_INFO_REQUEST = 'PRODUCT_CREATE_INFO_REQUEST'
// export const PRODUCT_UPDATE_INFO_SUCCESS = 'PRODUCT_CREATE_INFO_SUCCESS'
// export const PRODUCT_UPDATE_INFO_FAIL = 'PRODUCT_CREATE_INFO_FAIL'
