# Generated by Django 4.1.4 on 2023-03-08 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_product_brand_brand_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brands',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
