# Generated by Django 4.1.4 on 2023-03-08 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_product_brands'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='product',
        ),
    ]
