# Generated by Django 4.1.4 on 2023-03-09 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_remove_brand_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
