# Generated by Django 4.1.4 on 2023-03-30 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_remove_category_product_product_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
