# Generated by Django 4.1.2 on 2023-05-02 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_remove_product_image_alter_productimage_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('section', models.CharField(max_length=200)),
                ('subsections', models.CharField(blank=True, max_length=200, null=True)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Subsection',
            fields=[
                ('subsection', models.CharField(max_length=200)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='sections',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
