# Generated by Django 4.1.2 on 2023-05-02 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_section_subsection_category_sections'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='sections',
        ),
        migrations.RemoveField(
            model_name='section',
            name='subsections',
        ),
        migrations.AddField(
            model_name='product',
            name='sections',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='subsections',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
