# Generated by Django 4.1.2 on 2023-05-05 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_remove_product_sections_section_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='product',
        ),
        migrations.AddField(
            model_name='section',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.category'),
        ),
    ]
