# Generated by Django 4.1.2 on 2023-05-10 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_remove_section_product_section_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subsection',
        ),
    ]
